version: '3.7'
services:
  nest-api:
    container_name: gloss-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3010
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:12
    container_name: postgres
    restart: always
    ports:
      - 3302:5432
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-db
