query partyDateByRefAndType ($party_ref: String!, $date_type: String!)
{
  partyDateByRefAndType(party_ref: $party_ref, date_type: $date_type){
    date_type
    party_ref
  }
}

query partyDateByRef ($party_ref: String!)
{
  	partyDateByRef(party_ref: $party_ref){
    	party_ref
    	date_type
  }
}

query partyAddrByRefAndType ($party_ref: String!, $addr_type: String!)
{
  partyAddressByRefAndType(party_ref: $party_ref, addr_type: $addr_type){
    addr_type
    party_ref
  }
}

query partyAddrByRef ($party_ref: String!)
{
  partyAddressByRef(party_ref: $party_ref){
    addr_type
    party_ref
  }
}


query partyDate{ 
  partyDate{
			party_ref
  }
}

query partyAddress {
  partyAddress{
    party_ref
    contact_title
  }
}

## Query Variables for Date and Address 

{"party_ref": "CMPX-JP",
"date_type": "DAST",
"addr_type": "HEAD"}




