## Insert Data
[
    {
        "party_ref": "TRADING",
        "party_type": "BOOK",
        "party_short_name": "TRADING",
        "party_long_name": "TRADING",
        "party_extra_long_name": "TRADING",
        "active_ind": "A",
        "version_date": "2021-01-25",
        "version_no": "1",
        "version_user": "JMARSDEN"
    },
    {
        "party_ref": "JASD00",
        "party_type": "DACC",
        "party_short_name": "JASD00",
        "party_long_name": "JASD00",
        "party_extra_long_name": "JASD00",
        "active_ind": "A",
        "version_date": "2021-01-27",
        "version_no": "1",
        "version_user": "JMARSDEN"
    },
    {
        "party_ref": "DEPO00",
        "party_type": "DEPO",
        "party_short_name": "DEPO00",
        "party_long_name": "DEPO00",
        "party_extra_long_name": "DEPO00",
        "active_ind": "A",
        "version_date": "2021-01-27",
        "version_no": "1",
        "version_user": "JMARSDEN"
    },
    {
        "party_ref": "BVCP_JP_BR1",
        "party_type": "SECP",
        "party_short_name": "JP BROKER",
        "party_long_name": "JP BROKER",
        "party_extra_long_name": "JP BROKER",
        "active_ind": "A",
        "version_date": "2021-01-27",
        "version_no": "1",
        "version_user": "SQL_UTIL"
    },
    {
        "party_ref": "BVCP_JP_CL2",
        "party_type": "SECP",
        "party_short_name": "JP CUST CLIENT",
        "party_long_name": "JP CUSTODY CLIENT",
        "party_extra_long_name": "JP CUSTODY CLIENT",
        "active_ind": "A",
        "version_date": "2021-01-27",
        "version_no": "1",
        "version_user": "SQL_UTIL"
    },
    {
        "party_ref": "BVCP_JP_CL3",
        "party_type": "SECP",
        "party_short_name": "JP DVP CLIENT",
        "party_long_name": "JP DVP CLIENT",
        "party_extra_long_name": "JP DVP CLIENT",
        "active_ind": "A",
        "version_date": "2021-01-27",
        "version_no": "1",
        "version_user": "SQL_UTIL"
    },
    {
        "party_ref": "JASD98",
        "party_type": "DACC",
        "party_short_name": "JASD99",
        "party_long_name": "JASD98",
        "party_extra_long_name": "JASD98",
        "active_ind": "A",
        "version_date": "2021-01-27",
        "version_no": "2",
        "version_user": "ADMIN"
    },
    {
        "party_ref": "JASD60",
        "party_type": "DACC",
        "party_short_name": "JASD60",
        "party_long_name": "JASD60 NEW",
        "party_extra_long_name": "JASD60",
        "active_ind": "A",
        "version_date": "2021-01-28",
        "version_no": "2",
        "version_user": "ADMIN"
    },
    {
        "party_ref": "C029",
        "party_type": "COMP",
        "party_short_name": "Barc Secs Financing",
        "party_long_name": "Barclays Securities Financing",
        "party_extra_long_name": "Barclays Securities Financing",
        "active_ind": "A",
        "version_date": "2021-03-10",
        "version_no": "3",
        "version_user": "ADMIN"
    },
    {
        "party_ref": "C031",
        "party_type": "COMP",
        "party_short_name": "BB PLC AUS2",
        "party_long_name": "Barclays Bank PLC Australia (BBAS)",
        "party_extra_long_name": "Barclays Bank PLC Australia (BBAS)",
        "active_ind": "A",
        "version_date": "2021-03-13",
        "version_no": "12",
        "version_user": "ADMIN"
    },
    {
        "party_ref": "C030",
        "party_type": "COMP",
        "party_short_name": "BB PLC AUS2",
        "party_long_name": "Barclays Bank PLC Australia (BBAS)",
        "party_extra_long_name": "Barclays Bank PLC Australia (BBAS)",
        "active_ind": "A",
        "version_date": "2021-03-13",
        "version_no": "14",
        "version_user": "ADMIN"
    },
    {
        "party_ref": "CMP4",
        "party_type": "COMP",
        "party_short_name": "BR SEC JAPAN",
        "party_long_name": "BR SEC JAPAN",
        "party_extra_long_name": "BR SEC JAPAN",
        "active_ind": "A",
        "version_date": "2021-03-13",
        "version_no": "1",
        "version_user": "JMARSDEN"
    }
]
